      fprintf(stdout, "<meta charset=\"UTF-8\" />\n");
      fprintf(stdout, "<meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\" />\n");
      fprintf(stdout, "<meta name=\"apple-mobile-web-app-capable\" content=\"yes\" />\n");
      fprintf(stdout, "<style type=\"text/css\">\n");
      fprintf(stdout, "  body { color: #fc3; background-color: #000;\n");
      fprintf(stdout, "         overflow: hidden; zoom: 1; width: 100%; height: 100%; }\n");
//      fprintf(stdout, "  * { -webkit-overflow-scrolling: touch; }\n");
      fprintf(stdout, "  body b { color: #27f; }\n");
      fprintf(stdout, "  .clr0 { color: #3f0; }\n");
      fprintf(stdout, "  .clr1 { color: #ff3; }\n");
      fprintf(stdout, "  .clr2 { color: #e00; }\n");
      fprintf(stdout, "  .clr3 { color: #eee; }\n");
      fprintf(stdout, "  .clr4 { color: #ee0; }\n");
      fprintf(stdout, "  .clr5 { color: #0ee; }\n");
      fprintf(stdout, "  .clr6 { color: #e0e; }\n");
//      fprintf(stdout, "  .set > .clr6 { color: #fff; }\n");
      fprintf(stdout, "  .clr7 { color: #0af; }\n");
      fprintf(stdout, "  .set > .clr7 { color: #3cf; }\n");
      fprintf(stdout, "  .clr8 { color: #ff0; }\n");
      fprintf(stdout, "  .clr9 { background-color: #0e0; opacity: 0.1; }\n");
      fprintf(stdout, "  #inbox { position: absolute; left: 0; right: 0; float: left;\n");
      fprintf(stdout, "    font-size: 16px; top: 0; bottom: 0;\n");
      fprintf(stdout, "    border-radius: 5px; padding: 0; font-family: monospace;\n");
//      fprintf(stdout, "    border: #b3b solid 1px; margin: 8px;\n");
      fprintf(stdout, "    background-color: rgba(221, 51, 221, 0.1); z-index: 5; }\n");
      fprintf(stdout, "  #inbox > div { position: absolute; margin: 8px; padding: 8px;\n");
      fprintf(stdout, "    border-radius: 5px; border: #888 solid 1px; z-index: 10;\n");
      fprintf(stdout, "    background-color: rgba(101, 101, 101, 0.2); font-size: 16px; overflow: auto; }\n");
      fprintf(stdout, "  #inbox > div.act { display: block; z-index: 15;\n");
      fprintf(stdout, "    border-color: #dd3; background-color: rgba(221, 221, 51, 0.2); }\n");
      fprintf(stdout, "  #inbox > div.vis { display: block; }\n");
      fprintf(stdout, "  #inbox > div.esc { display: block;\n");
      fprintf(stdout, "    border-color: #3d3; background-color: rgba(51, 221, 51, 0.2); }\n");
      fprintf(stdout, "  #inbox > div.esc > div { visibility: hidden; }\n");
      fprintf(stdout, "  #inbox > div.esc > div:first-child { visibility: visible; }\n");
      fprintf(stdout, "  #inbox > div.eth { display: block;\n");
      fprintf(stdout, "    border-color: #dd3; opacity: 0.2; }\n");
      fprintf(stdout, "  #inbox > div.off { display: none; }\n");
//      fprintf(stdout, "  #inbox > div { position: relative; float: left; clear: left; width: 100%; }\n");
      fprintf(stdout, "  #inbox > div > div\n");
      fprintf(stdout, "    { position: relative; display: inline-block; width: 100%;\n");
      fprintf(stdout, "      white-space: normal; z-index: 10; }\n");
      fprintf(stdout, "  #inbox > div > div > b.lnum\n");
      fprintf(stdout, "    { position: relative; display: inline-block; width: 32px; float: left;\n");
      fprintf(stdout, "      text-align: right; padding-right: 16px; overflow: visible; clear: left; }\n");
      fprintf(stdout, "  #inbox > div > div > div.line\n");
      fprintf(stdout, "    { position: relative; display: inline-block; font-size: 14px;\n");
      fprintf(stdout, "      white-space: nowrap; z-index: 10; float: left; clear: none; }\n");
      fprintf(stdout, "  #inbox > div > div > div.subline\n");
      fprintf(stdout, "    { position: relative; display: inline-block; font-size: 12px; float: left;\n");
      fprintf(stdout, "      white-space: nowrap; z-index: 10; padding-left: 54px; clear: left; }\n");
      fprintf(stdout, "  #inbox > div > div > div > b:hover { border-left: #fc3 solid 4px; cursor: none; }\n");
      fprintf(stdout, "  #inbox > div > div.linezero {\n");
      fprintf(stdout, "    margin-left: -2px; width: 2px; overflow: visible; }\n"); // z-index: 11
      fprintf(stdout, "  #inbox > div > div.linezerosel {\n");
      fprintf(stdout, "    background-color: #017;\n");
      fprintf(stdout, "    width: 100%; overflow: visible; }\n");
      fprintf(stdout, "  #inbox > div > div.linezeroset {\n");
      fprintf(stdout, "    background-color: #028;\n");
      fprintf(stdout, "    width: 100%; overflow: visible; }\n");
      fprintf(stdout, "  #inbox > div > div.linezerosel > b.bluewisp {\n");
      fprintf(stdout, "    border-left-color: #fff; border-right-color: #fff;\n");
      fprintf(stdout, "    overflow: visible; }\n");
      fprintf(stdout, "  #inbox > div > div.linezeroset > b.bluewisp {\n");
      fprintf(stdout, "    border-left-color: #f0f; border-right-color: #f0f;\n");
      fprintf(stdout, "    overflow: visible; }\n");
      fprintf(stdout, "  #inbox > div > div.linezerofill {\n");
      fprintf(stdout, "    background-color: #00f;\n");
      fprintf(stdout, "    width: 100%; height: 100%; overflow: visible; }\n");
      fprintf(stdout, "  #inbox > div > div.linezerofillsel {\n");
      fprintf(stdout, "    background-color: #f0f;\n");
      fprintf(stdout, "    width: 100%; height: 100%; overflow: visible; }\n");
//      fprintf(stdout, "  #inbox > div > b:first-child { display: inline-block;\n");
//      fprintf(stdout, "    text-align: right; width: 30px; padding-right: 8px; }\n");
//      fprintf(stdout, "  #inbox > div > pre { position: absolute; top: 0; right: 0; color: #ff0;\n");
//      fprintf(stdout, "    font-size: 8px; }\n");
//      fprintf(stdout, "  #inbox > div > div { float: left; clear: left; word-wrap: break-word; }\n");
//      fprintf(stdout, "  #inbox > div > b {\n");
//      fprintf(stdout, "    text-shadow: -1px -1px 0px #777, 1px 1px 0px #444;\n");
//      fprintf(stdout, "  }\n");
      fprintf(stdout, "  #inbox > div > div > div > b {\n");
      fprintf(stdout, "    text-shadow: 1px 1px 0px #444;\n");
      fprintf(stdout, "  }\n");
      fprintf(stdout, "  #inbox > div > div > div > iframe {\n");
      fprintf(stdout, "    float: right; clear: none;\n");
      fprintf(stdout, "    width: 50px; height: 20px; margin: 2px;\n");
      fprintf(stdout, "    border: #f0f solid 1px; border-radius: 4px;\n");
      fprintf(stdout, "  }\n");
//      fprintf(stdout, "  body span > div#editor { position: absolute; width: 200px; height: 50px; bottom: -50px;\n");
//      fprintf(stdout, "    background-color: #da1; border: #fc3 solid 1px; }\n");
//      fprintf(stdout, "  body span > b.wisp { background-color: #00f; width: 5px; height: 100%; text-shadow: none; }\n");
//      fprintf(stdout, "  b.lnumstrike { display: inline-block; width: 32px;\n");
//      fprintf(stdout, "    text-align: right; padding-right: 16px; overflow: visible;\n");
//      fprintf(stdout, "    color: #777; text-decoration: line-through; }\n");
      fprintf(stdout, "  b.input { color: #00f; }\n");
      fprintf(stdout, "  b.output { color: #00f; }\n");
      fprintf(stdout, "  b.label { color: #fff; }\n");
      fprintf(stdout, "  b.command { color: #ff0; }\n");
      fprintf(stdout, "  b.context { color: #f0f; }\n");
      fprintf(stdout, "  b.rsqb {\n");
      fprintf(stdout, "    margin-left: -6px; color: #c11; }\n"); // text-decoration: line-through; }\n");
      fprintf(stdout, "  b.wisp + b.rsqb {\n");
      fprintf(stdout, "    color: #ccc; text-shadow: none !important; }\n");
      fprintf(stdout, "  b.rsqb + b.dash {\n");
      fprintf(stdout, "    color: #888; text-decoration: line-through; }\n");
      fprintf(stdout, "  b.rsqb + b.dash ~ b {\n");
      fprintf(stdout, "    color: #888; text-decoration: line-through; }\n");
      fprintf(stdout, "  b.rsqb + b.wisp + b.dash {\n");
      fprintf(stdout, "    color: #c11; text-decoration: none; }\n");
      fprintf(stdout, "  b.rsqb + b.wisp + b.dash ~ b {\n");
      fprintf(stdout, "    color: #c11; text-decoration: none; }\n");
      fprintf(stdout, "  b.rsqb + b.score {\n");
      fprintf(stdout, "    color: #ccc; }\n"); // border-bottom: #ff3 solid 1px; }\n");
      fprintf(stdout, "  b.rsqb + b.equals {\n");
      fprintf(stdout, "    color: #ccc; }\n"); // border-bottom: #3ff solid 1px; }\n");
      fprintf(stdout, "  b.action { color: #fff; }\n");
      fprintf(stdout, "  b.actend { color: #fff; }\n");
      fprintf(stdout, "  b.wisp + b.action { color: #0e0; }\n");
      fprintf(stdout, "  b.wisp + b.action ~ b.clr0 { color: #ee0; }\n");
      fprintf(stdout, "  b.wisp + b.action ~ b.actend { color: #0e0; }\n");
      fprintf(stdout, "  b.wisp + b.action ~ b.actend ~ b.action { color: #fff; }\n");
      fprintf(stdout, "  b.wisp + b.action ~ b.actend ~ b.action ~ b.actend { color: #fff; }\n");
      fprintf(stdout, "  b.wisp + b.action ~ b.actend ~ b.clr0 { color: #0e0; }\n");
//      fprintf(stdout, "  b.lnum ~ b.rsqb ~ b.action + b.wisp ~ b.actend { color: #fc3; }\n");
//      fprintf(stdout, "  b.lnum ~ b.rsqb ~ b.action + b.wisp ~ b.actend ~ b.action { color: #eee; }\n");
//      fprintf(stdout, "  b.rsqb ~ b.action + b.wisp ~ b.actend ~ b.action ~ b.clr0 { color: #3f0; }\n");
      fprintf(stdout, "  b.rsqb ~ b.tag { color: #e00; }\n");
//     fprintf(stdout, "  b.lnum ~ b.rsqb ~ b.tag ~ b.clr5 { color: #e00; }\n");
//      fprintf(stdout, "  b.lnum ~ b.rsqb ~ b.wisp + b.action ~ b.actend ~ b.action ~ b.actend { color: #eee; }\n");
//      fprintf(stdout, "  b.lnum ~ b.rsqb + b.score ~ b {\n");
//      fprintf(stdout, "    border-bottom: #ff3 solid 1px; }\n");
//      fprintf(stdout, "    border-left: #ccc solid 1px; border-right: #ccc solid 1px;\n");
//      fprintf(stdout, "    border-radius: 5px; background-color: #fc3; color: #111; }\n");
//      fprintf(stdout, "  #inbox > div > div > div.line > b.wisp {\n");
      fprintf(stdout, "  #inbox > div > div   b.wisp {\n");
      fprintf(stdout, "    border-left: #ccc solid 1px; border-right: #ccc solid 1px; float: none;\n");
      fprintf(stdout, "    border-radius: 5px; background-color: #fc3; color: #111; clear: none; }\n");
      fprintf(stdout, "  #inbox > div > div > b.wisp { margin-left: -8px; padding-right: 8px; float: left;\n");
      fprintf(stdout, "    border-radius: 10px; background-color: #222; color: #555; clear: none; }\n");
//      fprintf(stdout, "  #inbox > div > div > div.subline > b.wisp {\n");
//      fprintf(stdout, "    border-left: #ccc solid 1px; border-right: #ccc solid 1px;\n");
//      fprintf(stdout, "    border-radius: 5px; background-color: #fc3; color: #111; }\n");
      fprintf(stdout, "  b.redwisp { border-left: #c00 solid 1px; border-right: #c00 solid 1px;\n");
      fprintf(stdout, "    border-radius: 5px; background-color: #fc3; color: #d11; }\n");
      fprintf(stdout, "  b.bluewisp { border-left: #c00 solid 1px; border-right: #c00 solid 1px;\n");
      fprintf(stdout, "    border-radius: 5px; background-color: #fff; color: #111; }\n");
      fprintf(stdout, "  #inbox > div > div.nor { background-color: none; }\n");
      fprintf(stdout, "  #inbox > div > div.nor:hover { background-color: #223; }\n");
      fprintf(stdout, "  #inbox > div > div.sel { background-color:  rgba(0, 17, 119, 0.7); }\n"); // #017; }\n");
      fprintf(stdout, "  #inbox > div > div.sel:hover { background-color: rgba(34, 51, 136, 0.7); }\n"); // #238; }\n");
      fprintf(stdout, "  #inbox > div > div.els { background-color: rgba(34, 34, 85, 0.7); }\n"); // #225; }\n");
      fprintf(stdout, "  #inbox > div > div.els:hover { background-color: rgba(51, 51, 102, 0.7); }\n"); // #336; }\n");
      fprintf(stdout, "  #inbox > div > div.set { background-color: rgba(0, 34, 136, 0.7); }\n"); // #028; }\n");
      fprintf(stdout, "  #inbox > div > div.set:hover { background-color: rgba(17, 51, 153, 0.7); cursor: pointer; }\n"); // 139
//      fprintf(stdout, "  #inbox > div > div.set { background-color: #eb0; }\n");
      fprintf(stdout, "  #inbox > div > div.mod { background-color: rgba(85, 17, 0, 0.7); }\n"); // 510
      fprintf(stdout, "  #inbox > div > div.sol { background-color: rgba(85, 17, 0, 0.7); }\n");
      fprintf(stdout, "  #inbox > div > div.mak { background-color: rgba(17, 85, 0, 0.7); }\n");
      fprintf(stdout, "  #inbox > div > div.sal { background-color: rgba(17, 85, 0, 0.7); }\n");
      fprintf(stdout, "  #inbox > div > div.muk { background-color: rgba(85, 17, 0, 0.7); }\n");
      fprintf(stdout, "  #inbox > div > div.mix { background-color: rgba(17, 85, 0, 0.7); }\n");
      fprintf(stdout, "  #inbox > div > div.sox { background-color: rgba(17, 85, 0, 0.7); }\n");
      fprintf(stdout, "  #inbox > div > div.fix { background: transparent; transition: all 1s; }\n");
      fprintf(stdout, "  #inbox > div > div.fix:hover { background-color: rgba(34, 34, 51, 0.7); }\n"); // 223
      fprintf(stdout, "  #inbox > div > div.six { background-color: rgba(0, 17, 119, 0.7); transition: all 1s; }\n");
      fprintf(stdout, "  #inbox > div > div.fly { background-color: rgba(68, 68, 0, 0.7); opacity: 0; transition: all 1s; }\n");
      fprintf(stdout, "  #inbox > div > div.die { background-color: rgba(68, 17, 0, 0.7); height: 0; transition: all 1s; }\n");
      fprintf(stdout, "  #inbox > div > div.openline { position: absolute;\n");
      fprintf(stdout, "    top: 4px; left: 0; right: 0; bottom: 4px; border-radius: 8px;\n");
      fprintf(stdout, "    background-color: #000; }\n");
      fprintf(stdout, "  #inbox > div > div.openlinesel { position: absolute;\n");
      fprintf(stdout, "    top: 4px; left: 0; right: 0; bottom: 4px; border-radius: 8px;\n");
      fprintf(stdout, "    background-color: rgba(0, 17, 119, 0.5); }\n");
      fprintf(stdout, "  #inbox > div > div.openlineset { position: absolute;\n");
      fprintf(stdout, "    top: 4px; left: 0; right: 0; bottom: 4px; border-radius: 8px;\n");
      fprintf(stdout, "    background-color: rgba(0, 34, 136, 0.5); }\n");
      fprintf(stdout, "  #inbox > div > div:first-child + div { margin-top: 0.5em; }\n"); // for line 1
// maybe not using openbox?
      fprintf(stdout, "  #inbox > div > div > div.openbox { position: absolute;\n");
      fprintf(stdout, "    top: 16px; left: 16px; right: 16px; bottom: 16px;\n");
      fprintf(stdout, "    z-index: 1; border-radius: 8px; }\n");
//      fprintf(stdout, "  #inbox > div > div > div.openbox > .nul { border-top: #00f solid 1px; }\n");
//      fprintf(stdout, "  #inbox > div > div > div.openbox > .act { border-top: #0f0 solid 1px; }\n");
//      fprintf(stdout, "  #inbox > div > div > div.openbox > .err { border-top: #f00 solid 1px; }\n");
      fprintf(stdout, "  #inbox > div > div > div.openbox > iframe {\n");
      fprintf(stdout, "    position: absolute; border: none; border-radius: 16px;\n");
      fprintf(stdout, "    top: 0; bottom: 0; left: 0; right: 0;\n");
      fprintf(stdout, "    width: 100%; height: 100%; }\n");
      fprintf(stdout, "  #inbox > div > div > div.openbox > div { display: none;\n");
      fprintf(stdout, "    position: absolute; color: #fff; font-weight: bold;\n");
      fprintf(stdout, "    top: 0; bottom: 0; left: 0; right: 0;\n");
      fprintf(stdout, "    text-align: center; background-color: #000; opacity: 0.02; }\n");
      fprintf(stdout, "  #logbox { display: none; position: absolute; bottom: 0; right: 24px; font-size: 16px;\n");
      fprintf(stdout, "    border: #000 solid 1px; margin: 16px; padding: 2px; border-radius: 5px;\n");
      fprintf(stdout, "    text-align: left; background-color: rgba(51, 51, 221, 0.1); z-index: 10; }\n");
      fprintf(stdout, "  #optbox { display: none; position: absolute; top: 2px; right: 2px; font-size: 16px;\n");
      fprintf(stdout, "    border: #000 solid 1px; padding: 2px; border-radius: 5px;\n");
      fprintf(stdout, "    text-align: center; background-color: rgba(51, 51, 221, 0.1); z-index: 11; }\n");
      fprintf(stdout, "  #trigbox { display: none; position: absolute; text-align: center; width: 100px;\n");
      fprintf(stdout, "    bottom: 20px; left: 0; font-size: 12px; color: #fc3; }\n");
//      fprintf(stdout, "    border: #000 solid 1px; border-radius: 5px; padding: 2px; }\n");
      fprintf(stdout, "  #commbox0, #commbox1, #commbox2, #commbox3\n");
      fprintf(stdout, "  { position: absolute; border-radius: 5px; z-index: 10;\n");
      fprintf(stdout, "    border: #d33 solid 1px; margin: 32px; padding: 8px;\n");
      fprintf(stdout, "    text-align: left; background-color: rgba(221, 51, 51, 0.1);\n");
      fprintf(stdout, "    word-wrap: break-word; font-size: 12px; }\n");
      fprintf(stdout, "  #commbox0 { bottom: 6%; left: 46%; }\n");
      fprintf(stdout, "  #commbox1 { bottom: 46%; left: 46%; }\n");
      fprintf(stdout, "  #commbox2 { bottom: 6%; left: 6%; }\n");
      fprintf(stdout, "  #commbox3 { bottom: 46%; left: 6%; }\n");
      fprintf(stdout, "  #logtext { color: #ddd; }\n");
      fprintf(stdout, "  #logtext > b { color: #d00; }\n");
      fprintf(stdout, "  #logtext > u { text-decoration: none; }\n");
      fprintf(stdout, "  #logtext > u.o { color: #f3f; }\n");
      fprintf(stdout, "  #logtext > u.l { color: #fff; }\n");
      fprintf(stdout, "  #logtext > u.a { color: #3cf; }\n");
      fprintf(stdout, "  #logtext > u.r { color: #fc3; }\n");
      fprintf(stdout, "  #logtext > u.d { color: #f33; }\n");
      fprintf(stdout, "  #logtext > u.s { color: #3f3; }\n");
      fprintf(stdout, "  #iobox { position: absolute; top: 0; right: 0; width: 3px;\n");
      fprintf(stdout, "    height: 3px; overflow: hidden; z-index: -100;\n");
      fprintf(stdout, "    visibility: hidden; }\n");
      fprintf(stdout, "  #pastebox { position: absolute; z-index: 100;\n");
      fprintf(stdout, "    left: 50%; width: 50%; margin-left: -25%;\n");
      fprintf(stdout, "    bottom: 10%; height: 20%; margin-top: -10%;\n");
      fprintf(stdout, "    border: #fc3 solid 2px; border-radius: 4px;\n");
      fprintf(stdout, "    background-color: rgba(0, 0, 0, 0.5); overflow: visible; }\n");
//      fprintf(stdout, "    padding: 5px; }\n");
      fprintf(stdout, "  #pastebox > textarea { position: absolute; z-index: 101;\n");
//      fprintf(stdout, "    top: 0; left: 0; right: 0; bottom: 0;\n");
      fprintf(stdout, "    width: 100%; height: 100%; text-align: center;\n");
      fprintf(stdout, "    margin: 0; padding: 0; border: none; overflow: visible;\n");
      fprintf(stdout, "    background: none; color: #fc3; font-size: 12px;\n");
      fprintf(stdout, "  }\n");
      fprintf(stdout, "  #pastebox > a { position: absolute; word-wrap: break-word;\n");
      fprintf(stdout, "    width: 100%; height: 100%; text-align: center;\n");
      fprintf(stdout, "    background: none; color: #1bf; font-size: 14px; padding: 10px;\n");
      fprintf(stdout, "  }\n");
      fprintf(stdout, "  #pastebox > a:hover { cursor: pointer; color: #fc3; }\n");
      fprintf(stdout, "  #pastebox > a:active { color: #f1f; }\n");
//      fprintf(stdout, "    background: url(../@~/wisp.gif); background-size: 100% 100%;\n");
//      fprintf(stdout, "    background-position: center center; background-repeat: no-repeat; overflow: visible; }\n");
      fprintf(stdout, "  #loadbox { position: absolute; z-index: 101;\n");
      fprintf(stdout, "    left: 0; right: 0; top: 0; bottom: 0;\n");
      fprintf(stdout, "    border-radius: 8px; opacity: 0.75;\n");
      fprintf(stdout, "    background-color: rgba(0, 0, 0, 0.5); }\n");
      fprintf(stdout, "  #loadbox.vis { border: #f0f solid 1px; }\n");
      fprintf(stdout, "  #loadbox.act { border: #0f0 solid 1px; }\n");
      fprintf(stdout, "  #loadbox > iframe { background-color: #078;\n");
      fprintf(stdout, "    width: 100%; height: 100%; border: none; }\n");
      fprintf(stdout, "</style>\n");
